// Generated by https://quicktype.io

export interface WineDataModel {
  no: string;
  name: string;
  image: string;
  cost: Cost;
  tags: string[];
  details: string;
}

export interface Cost {
  bottle: number;
  case: number;
}
